### ISSUE TITLE
Update 2024.11.1 - ne radi više addon

### ISSUE THREAD

**Issue by zdimic1** [9a4gl/hass-centrometal-boiler#8]
Pozdrav,

Danas nakon updatea na 2024.11.1 addon ne radi.
Ima li možda kakav update addona?

Hvala

**Comment by zdimic1** [comment]
Danas je u nekom momentu proradio na par sati (ne mogu povezati zašto), ali nakon reboot-a routera ponovo Boiler not available...
Probao sam:
restart routera - ne pomaže
restart HA - ne pomaže
restart kotla - ne pomaže 
Brisanje i ponovno dodavanje addona - ne pomaže 
roll back HA na prijašnju verziju - ne pomaže

**Comment by CycloneHR** [comment]
Isus stvar i kod mene, nakon update-a na 24.1.11 više ne radi ☹️

**Comment by zdimic1** [comment]
U logu meni javlja ovo:

2024-11-15 10:30:56.125 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/centrometal_web_boiler/ws/client.py", line 97, in __main
    self.connection = await websockets.connect(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/websockets/asyncio/client.py", line 441, in __await_impl__
    self.connection = await self.create_connection()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/websockets/asyncio/client.py", line 367, in create_connection
    _, connection = await loop.create_connection(factory, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BaseEventLoop.create_connection() got an unexpected keyword argument 'create_protocol'

**Comment by zdimic1** [comment]
Također sam naletio na warning (pretpostavljam da ovo nije uzrok problema) u Logu:

2024-11-15 10:30:02.496 WARNING (MainThread) [homeassistant.helpers.frame] Detected code that calls async_forward_entry_setup for integration centrometal_boiler with title: PelTec-lambda: Ul. Dr.XXXXXXXXX, Zagreb  and entry_id: XXXXXXXXXXXXXXX, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.
Stack (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2318, in async_forward_entry_setup
    _report_non_awaited_platform_forwards(entry, "async_forward_entry_setup")
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1194, in _report_non_awaited_platform_forwards
    report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 156, in report
    _LOGGER.warning(msg, stack_info=True)

**Comment by zdimic1** [comment]
Iskopao sam i ovaj warning

Detected blocking call to load_default_certs with args (<ssl.SSLContext object at 0x7f884fd350>, <Purpose.SERVER_AUTH: _ASN1Object(nid=129, shortname='serverAuth', longname='TLS Web Server Authentication', oid='1.3.6.1.5.5.7.3.1')>) inside the event loop by custom integration 'centrometal_boiler' at custom_components/centrometal_boiler/__init__.py, line 143: await self.web_boiler_client.start_websocket(self.on_parameter_updated) (offender: /usr/local/lib/python3.12/ssl.py, line 713: context.load_default_certs(purpose)), please create a bug report at https://github.com/9a4gl/hass-centrometal-boiler/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_default_certs Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 783, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 546, in async_setup await self.__async_setup_with_context(hass, integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context result = await component.async_setup_entry(hass, self) File "/config/custom_components/centrometal_boiler/__init__.py", line 59, in async_setup_entry if not await web_boiler_system.start(): File "/config/custom_components/centrometal_boiler/__init__.py", line 143, in start await self.web_boiler_client.start_websocket(self.on_parameter_updated)

**Comment by CycloneHR** [comment]
Update na 2024.11.2, nažalost i dalje me radi.

**Comment by 9a4gl** [comment]
Nadam se da ću imati vremena sljedeći tjedan pogledati problem. Posljednjih dana jednostavno nemam vremena za nikakav hobi.

**Comment by serviser** [comment]
kod mene je danas proradilo nakon nekoliko dana nedjelovanja...

**Comment by 9a4gl** [comment]
Pushao sam novu verziju. 0.0.52, trebalo bi biti sada ok

**Comment by CycloneHR** [comment]
Nakon update-a na 0.0.52 ponovo je sve OK. 
Hvala puno na intervenciji.

**Comment by zdimic1** [comment]
Potvrđujem, sad sve radi. Puno hvala.
